
from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1341, 662)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.frame.setFont(font)
        self.frame.setStyleSheet("border-style: solid;\n"
"border-width: 1px;\n"
"border-radius: 10px;\n"
"background-color: rgb(0, 0, 0);")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame)
        self.verticalLayout.setObjectName("verticalLayout")
        self.titulo = QtWidgets.QFrame(self.frame)
        self.titulo.setMinimumSize(QtCore.QSize(0, 42))
        self.titulo.setStyleSheet("border-style: solid;\n"
"border-width: 1px;\n"
"border-radius: 5px;\n"
"background-color: rgb(128, 128, 128);\n"
"")
        self.titulo.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.titulo.setFrameShadow(QtWidgets.QFrame.Raised)
        self.titulo.setObjectName("titulo")
        self.label_43 = QtWidgets.QLabel(self.titulo)
        self.label_43.setGeometry(QtCore.QRect(520, 10, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_43.setObjectName("label_43")
        self.rbtn_cliente = QtWidgets.QRadioButton(self.titulo)
        self.rbtn_cliente.setGeometry(QtCore.QRect(350, 40, 82, 17))
        self.rbtn_cliente.setObjectName("rbtn_cliente")
        self.rbtn_producto = QtWidgets.QRadioButton(self.titulo)
        self.rbtn_producto.setGeometry(QtCore.QRect(850, 40, 82, 17))
        self.rbtn_producto.setObjectName("rbtn_producto")
        self.verticalLayout.addWidget(self.titulo)
        self.contenido = QtWidgets.QFrame(self.frame)
        self.contenido.setStyleSheet("border-style: solid;\n"
"border-width: 2px;\n"
"border-radius: 5px;\n"
"background-color: rgb(0, 0, 0);")
        self.contenido.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.contenido.setFrameShadow(QtWidgets.QFrame.Raised)
        self.contenido.setObjectName("contenido")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.contenido)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.menu = QtWidgets.QFrame(self.contenido)
        self.menu.setMinimumSize(QtCore.QSize(200, 0))
        self.menu.setMaximumSize(QtCore.QSize(0, 16777215))
        self.menu.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.menu.setObjectName("menu")
        self.btn_base_datos = QtWidgets.QPushButton(self.menu)
        self.btn_base_datos.setGeometry(QtCore.QRect(20, 20, 141, 41))
        self.btn_base_datos.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_base_datos.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.btn_base_datos.setObjectName("btn_base_datos")
        self.btn_registrar = QtWidgets.QPushButton(self.menu)
        self.btn_registrar.setGeometry(QtCore.QRect(20, 80, 141, 41))
        self.btn_registrar.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_registrar.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.btn_registrar.setObjectName("btn_registrar")
        self.btn_actualizar = QtWidgets.QPushButton(self.menu)
        self.btn_actualizar.setGeometry(QtCore.QRect(20, 140, 141, 41))
        self.btn_actualizar.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_actualizar.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.btn_actualizar.setObjectName("btn_actualizar")
        self.btn_eliminar = QtWidgets.QPushButton(self.menu)
        self.btn_eliminar.setGeometry(QtCore.QRect(20, 200, 141, 41))
        self.btn_eliminar.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_eliminar.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.btn_eliminar.setObjectName("btn_eliminar")
        self.btn_reporte_mensual = QtWidgets.QPushButton(self.menu)
        self.btn_reporte_mensual.setGeometry(QtCore.QRect(20, 410, 141, 51))
        self.btn_reporte_mensual.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_reporte_mensual.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.btn_reporte_mensual.setObjectName("btn_reporte_mensual")
        self.btn_reporte_semanal = QtWidgets.QPushButton(self.menu)
        self.btn_reporte_semanal.setGeometry(QtCore.QRect(20, 470, 141, 51))
        self.btn_reporte_semanal.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_reporte_semanal.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.btn_reporte_semanal.setObjectName("btn_reporte_semanal")
        self.btn_venta = QtWidgets.QPushButton(self.menu)
        self.btn_venta.setGeometry(QtCore.QRect(20, 350, 141, 51))
        self.btn_venta.setMinimumSize(QtCore.QSize(40, 0))
        self.btn_venta.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.btn_venta.setObjectName("btn_venta")
        self.horizontalLayout_2.addWidget(self.menu)
        self.vista = QtWidgets.QFrame(self.contenido)
        self.vista.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.vista.setFrameShadow(QtWidgets.QFrame.Raised)
        self.vista.setObjectName("vista")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.vista)
        self.horizontalLayout_3.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.contenedor_paginas = QtWidgets.QStackedWidget(self.vista)
        self.contenedor_paginas.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"")
        self.contenedor_paginas.setObjectName("contenedor_paginas")
        self.vacio = QtWidgets.QWidget()
        self.vacio.setObjectName("vacio")
        self.label_50 = QtWidgets.QLabel(self.vacio)
        self.label_50.setGeometry(QtCore.QRect(120, 80, 901, 451))
        self.label_50.setText("")
        self.label_50.setObjectName("label_50")
        self.label_54 = QtWidgets.QLabel(self.vacio)
        self.label_54.setGeometry(QtCore.QRect(390, 10, 321, 61))
        self.label_54.setStyleSheet("font: 75 24pt \"MS Shell Dlg 2\";\n"
"")
        self.label_54.setObjectName("label_54")
        self.contenedor_paginas.addWidget(self.vacio)
        self.bd_cliente = QtWidgets.QWidget()
        self.bd_cliente.setObjectName("bd_cliente")
        self.tabla_cliente = QtWidgets.QTableWidget(self.bd_cliente)
        self.tabla_cliente.setGeometry(QtCore.QRect(230, 140, 541, 381))
        self.tabla_cliente.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.tabla_cliente.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_cliente.setObjectName("tabla_cliente")
        self.tabla_cliente.setColumnCount(5)
        self.tabla_cliente.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_cliente.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_cliente.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_cliente.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_cliente.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_cliente.setHorizontalHeaderItem(4, item)
        self.label_36 = QtWidgets.QLabel(self.bd_cliente)
        self.label_36.setGeometry(QtCore.QRect(330, 10, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_36.setObjectName("label_36")
        self.label_57 = QtWidgets.QLabel(self.bd_cliente)
        self.label_57.setGeometry(QtCore.QRect(370, 80, 61, 31))
        self.label_57.setObjectName("label_57")
        self.txt_busca_bd_cliente = QtWidgets.QLineEdit(self.bd_cliente)
        self.txt_busca_bd_cliente.setGeometry(QtCore.QRect(470, 80, 161, 31))
        self.txt_busca_bd_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_busca_bd_cliente.setObjectName("txt_busca_bd_cliente")
        self.contenedor_paginas.addWidget(self.bd_cliente)
        self.bd_producto = QtWidgets.QWidget()
        self.bd_producto.setObjectName("bd_producto")
        self.tabla_producto = QtWidgets.QTableWidget(self.bd_producto)
        self.tabla_producto.setGeometry(QtCore.QRect(260, 130, 521, 371))
        self.tabla_producto.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.tabla_producto.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_producto.setObjectName("tabla_producto")
        self.tabla_producto.setColumnCount(5)
        self.tabla_producto.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto.setHorizontalHeaderItem(4, item)
        self.label_37 = QtWidgets.QLabel(self.bd_producto)
        self.label_37.setGeometry(QtCore.QRect(320, 10, 361, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_37.setObjectName("label_37")
        self.label_58 = QtWidgets.QLabel(self.bd_producto)
        self.label_58.setGeometry(QtCore.QRect(360, 70, 61, 31))
        self.label_58.setObjectName("label_58")
        self.txt_busca_bd_producto = QtWidgets.QLineEdit(self.bd_producto)
        self.txt_busca_bd_producto.setGeometry(QtCore.QRect(480, 70, 161, 31))
        self.txt_busca_bd_producto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_busca_bd_producto.setObjectName("txt_busca_bd_producto")
        self.contenedor_paginas.addWidget(self.bd_producto)
        self.registra_cliente = QtWidgets.QWidget()
        self.registra_cliente.setObjectName("registra_cliente")
        self.label_5 = QtWidgets.QLabel(self.registra_cliente)
        self.label_5.setGeometry(QtCore.QRect(360, 120, 81, 31))
        self.label_5.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.registra_cliente)
        self.label_6.setGeometry(QtCore.QRect(360, 180, 51, 31))
        self.label_6.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.registra_cliente)
        self.label_7.setGeometry(QtCore.QRect(360, 240, 31, 31))
        self.label_7.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(self.registra_cliente)
        self.label_8.setGeometry(QtCore.QRect(360, 300, 71, 31))
        self.label_8.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(self.registra_cliente)
        self.label_9.setGeometry(QtCore.QRect(360, 360, 51, 31))
        self.label_9.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_9.setObjectName("label_9")
        self.txt_cod_cliente = QtWidgets.QLineEdit(self.registra_cliente)
        self.txt_cod_cliente.setEnabled(False)
        self.txt_cod_cliente.setGeometry(QtCore.QRect(470, 120, 81, 31))
        self.txt_cod_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_cod_cliente.setObjectName("txt_cod_cliente")
        self.txt_nombre_cliente = QtWidgets.QLineEdit(self.registra_cliente)
        self.txt_nombre_cliente.setGeometry(QtCore.QRect(470, 180, 161, 31))
        self.txt_nombre_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_nombre_cliente.setObjectName("txt_nombre_cliente")
        self.txt_dni_cliente = QtWidgets.QLineEdit(self.registra_cliente)
        self.txt_dni_cliente.setGeometry(QtCore.QRect(470, 240, 161, 31))
        self.txt_dni_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_dni_cliente.setObjectName("txt_dni_cliente")
        self.txt_telefono_cliente = QtWidgets.QLineEdit(self.registra_cliente)
        self.txt_telefono_cliente.setGeometry(QtCore.QRect(470, 300, 161, 31))
        self.txt_telefono_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_telefono_cliente.setObjectName("txt_telefono_cliente")
        self.cmb_sexo_cliente = QtWidgets.QComboBox(self.registra_cliente)
        self.cmb_sexo_cliente.setGeometry(QtCore.QRect(470, 360, 161, 31))
        self.cmb_sexo_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmb_sexo_cliente.setObjectName("cmb_sexo_cliente")
        self.cmb_sexo_cliente.addItem("")
        self.cmb_sexo_cliente.setItemText(0, "")
        self.cmb_sexo_cliente.addItem("")
        self.cmb_sexo_cliente.addItem("")
        self.btn_limpiar_cliente = QtWidgets.QPushButton(self.registra_cliente)
        self.btn_limpiar_cliente.setGeometry(QtCore.QRect(720, 240, 75, 23))
        self.btn_limpiar_cliente.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_limpiar_cliente.setObjectName("btn_limpiar_cliente")
        self.btn_registrar_cliente = QtWidgets.QPushButton(self.registra_cliente)
        self.btn_registrar_cliente.setGeometry(QtCore.QRect(720, 350, 121, 51))
        self.btn_registrar_cliente.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_registrar_cliente.setObjectName("btn_registrar_cliente")
        self.label_38 = QtWidgets.QLabel(self.registra_cliente)
        self.label_38.setGeometry(QtCore.QRect(360, 30, 261, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_38.setObjectName("label_38")
        self.contenedor_paginas.addWidget(self.registra_cliente)
        self.registra_producto = QtWidgets.QWidget()
        self.registra_producto.setObjectName("registra_producto")
        self.label_10 = QtWidgets.QLabel(self.registra_producto)
        self.label_10.setGeometry(QtCore.QRect(290, 140, 101, 31))
        self.label_10.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.registra_producto)
        self.label_11.setGeometry(QtCore.QRect(290, 380, 71, 31))
        self.label_11.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.registra_producto)
        self.label_12.setGeometry(QtCore.QRect(290, 320, 61, 31))
        self.label_12.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.registra_producto)
        self.label_13.setGeometry(QtCore.QRect(290, 260, 61, 31))
        self.label_13.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.registra_producto)
        self.label_14.setGeometry(QtCore.QRect(290, 200, 51, 31))
        self.label_14.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_14.setObjectName("label_14")
        self.txt_cod_producto = QtWidgets.QLineEdit(self.registra_producto)
        self.txt_cod_producto.setEnabled(False)
        self.txt_cod_producto.setGeometry(QtCore.QRect(420, 140, 71, 31))
        self.txt_cod_producto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_cod_producto.setObjectName("txt_cod_producto")
        self.txt_tipo_producto = QtWidgets.QLineEdit(self.registra_producto)
        self.txt_tipo_producto.setGeometry(QtCore.QRect(420, 200, 151, 31))
        self.txt_tipo_producto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_tipo_producto.setObjectName("txt_tipo_producto")
        self.txt_marca_producto = QtWidgets.QLineEdit(self.registra_producto)
        self.txt_marca_producto.setGeometry(QtCore.QRect(420, 260, 151, 31))
        self.txt_marca_producto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_marca_producto.setObjectName("txt_marca_producto")
        self.txt_cantidad_producto = QtWidgets.QLineEdit(self.registra_producto)
        self.txt_cantidad_producto.setGeometry(QtCore.QRect(420, 380, 151, 31))
        self.txt_cantidad_producto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_cantidad_producto.setObjectName("txt_cantidad_producto")
        self.txt_precio_producto = QtWidgets.QLineEdit(self.registra_producto)
        self.txt_precio_producto.setGeometry(QtCore.QRect(420, 320, 151, 31))
        self.txt_precio_producto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_precio_producto.setObjectName("txt_precio_producto")
        self.btn_limpiar_producto = QtWidgets.QPushButton(self.registra_producto)
        self.btn_limpiar_producto.setGeometry(QtCore.QRect(660, 260, 91, 21))
        self.btn_limpiar_producto.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_limpiar_producto.setObjectName("btn_limpiar_producto")
        self.btn_registar_producto = QtWidgets.QPushButton(self.registra_producto)
        self.btn_registar_producto.setGeometry(QtCore.QRect(660, 360, 121, 51))
        self.btn_registar_producto.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_registar_producto.setObjectName("btn_registar_producto")
        self.label_39 = QtWidgets.QLabel(self.registra_producto)
        self.label_39.setGeometry(QtCore.QRect(310, 30, 271, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_39.setObjectName("label_39")
        self.contenedor_paginas.addWidget(self.registra_producto)
        self.actualiza_cliente = QtWidgets.QWidget()
        self.actualiza_cliente.setObjectName("actualiza_cliente")
        self.tabla_actualiza_cliente = QtWidgets.QTableWidget(self.actualiza_cliente)
        self.tabla_actualiza_cliente.setGeometry(QtCore.QRect(30, 140, 501, 371))
        self.tabla_actualiza_cliente.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabla_actualiza_cliente.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.tabla_actualiza_cliente.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tabla_actualiza_cliente.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabla_actualiza_cliente.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_actualiza_cliente.setObjectName("tabla_actualiza_cliente")
        self.tabla_actualiza_cliente.setColumnCount(5)
        self.tabla_actualiza_cliente.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_actualiza_cliente.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_actualiza_cliente.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_actualiza_cliente.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_actualiza_cliente.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_actualiza_cliente.setHorizontalHeaderItem(4, item)
        self.btn_actualizar_cliente = QtWidgets.QPushButton(self.actualiza_cliente)
        self.btn_actualizar_cliente.setGeometry(QtCore.QRect(890, 430, 101, 41))
        self.btn_actualizar_cliente.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_actualizar_cliente.setObjectName("btn_actualizar_cliente")
        self.label_15 = QtWidgets.QLabel(self.actualiza_cliente)
        self.label_15.setGeometry(QtCore.QRect(560, 60, 81, 31))
        self.label_15.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.actualiza_cliente)
        self.label_16.setGeometry(QtCore.QRect(560, 130, 51, 31))
        self.label_16.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"")
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.actualiza_cliente)
        self.label_17.setGeometry(QtCore.QRect(560, 200, 51, 31))
        self.label_17.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"")
        self.label_17.setObjectName("label_17")
        self.label_18 = QtWidgets.QLabel(self.actualiza_cliente)
        self.label_18.setGeometry(QtCore.QRect(560, 340, 51, 31))
        self.label_18.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"")
        self.label_18.setObjectName("label_18")
        self.label_19 = QtWidgets.QLabel(self.actualiza_cliente)
        self.label_19.setGeometry(QtCore.QRect(560, 270, 71, 31))
        self.label_19.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"")
        self.label_19.setObjectName("label_19")
        self.txt_actualiza_cod_cliente = QtWidgets.QLineEdit(self.actualiza_cliente)
        self.txt_actualiza_cod_cliente.setEnabled(False)
        self.txt_actualiza_cod_cliente.setGeometry(QtCore.QRect(660, 60, 71, 31))
        self.txt_actualiza_cod_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_actualiza_cod_cliente.setObjectName("txt_actualiza_cod_cliente")
        self.txt_actualiza_nombre_cliente = QtWidgets.QLineEdit(self.actualiza_cliente)
        self.txt_actualiza_nombre_cliente.setGeometry(QtCore.QRect(660, 130, 131, 31))
        self.txt_actualiza_nombre_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_actualiza_nombre_cliente.setObjectName("txt_actualiza_nombre_cliente")
        self.txt_actualiza_dni = QtWidgets.QLineEdit(self.actualiza_cliente)
        self.txt_actualiza_dni.setGeometry(QtCore.QRect(660, 200, 131, 31))
        self.txt_actualiza_dni.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_actualiza_dni.setObjectName("txt_actualiza_dni")
        self.txt_actualiza_telefono = QtWidgets.QLineEdit(self.actualiza_cliente)
        self.txt_actualiza_telefono.setGeometry(QtCore.QRect(660, 270, 131, 31))
        self.txt_actualiza_telefono.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_actualiza_telefono.setObjectName("txt_actualiza_telefono")
        self.cmb_actualiza_sexo = QtWidgets.QComboBox(self.actualiza_cliente)
        self.cmb_actualiza_sexo.setGeometry(QtCore.QRect(660, 340, 131, 31))
        self.cmb_actualiza_sexo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmb_actualiza_sexo.setObjectName("cmb_actualiza_sexo")
        self.cmb_actualiza_sexo.addItem("")
        self.cmb_actualiza_sexo.setItemText(0, "")
        self.cmb_actualiza_sexo.addItem("")
        self.cmb_actualiza_sexo.addItem("")
        self.label_40 = QtWidgets.QLabel(self.actualiza_cliente)
        self.label_40.setGeometry(QtCore.QRect(140, 20, 251, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_40.setObjectName("label_40")
        self.btn_actualizar_cliente_limpia = QtWidgets.QPushButton(self.actualiza_cliente)
        self.btn_actualizar_cliente_limpia.setGeometry(QtCore.QRect(890, 310, 101, 31))
        self.btn_actualizar_cliente_limpia.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_actualizar_cliente_limpia.setObjectName("btn_actualizar_cliente_limpia")
        self.label_59 = QtWidgets.QLabel(self.actualiza_cliente)
        self.label_59.setGeometry(QtCore.QRect(130, 90, 61, 31))
        self.label_59.setObjectName("label_59")
        self.txt_busca_actualiza_cliente = QtWidgets.QLineEdit(self.actualiza_cliente)
        self.txt_busca_actualiza_cliente.setGeometry(QtCore.QRect(250, 90, 161, 31))
        self.txt_busca_actualiza_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_busca_actualiza_cliente.setObjectName("txt_busca_actualiza_cliente")
        self.contenedor_paginas.addWidget(self.actualiza_cliente)
        self.actualiza_producto = QtWidgets.QWidget()
        self.actualiza_producto.setObjectName("actualiza_producto")
        self.tabla_actualiza_producto = QtWidgets.QTableWidget(self.actualiza_producto)
        self.tabla_actualiza_producto.setGeometry(QtCore.QRect(30, 150, 511, 361))
        self.tabla_actualiza_producto.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.tabla_actualiza_producto.setTabKeyNavigation(False)
        self.tabla_actualiza_producto.setProperty("showDropIndicator", False)
        self.tabla_actualiza_producto.setDragEnabled(True)
        self.tabla_actualiza_producto.setDragDropOverwriteMode(False)
        self.tabla_actualiza_producto.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabla_actualiza_producto.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_actualiza_producto.setCornerButtonEnabled(True)
        self.tabla_actualiza_producto.setObjectName("tabla_actualiza_producto")
        self.tabla_actualiza_producto.setColumnCount(5)
        self.tabla_actualiza_producto.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_actualiza_producto.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_actualiza_producto.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_actualiza_producto.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_actualiza_producto.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_actualiza_producto.setHorizontalHeaderItem(4, item)
        self.label_20 = QtWidgets.QLabel(self.actualiza_producto)
        self.label_20.setGeometry(QtCore.QRect(560, 60, 91, 31))
        self.label_20.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"")
        self.label_20.setObjectName("label_20")
        self.label_21 = QtWidgets.QLabel(self.actualiza_producto)
        self.label_21.setGeometry(QtCore.QRect(560, 130, 51, 31))
        self.label_21.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"")
        self.label_21.setObjectName("label_21")
        self.label_22 = QtWidgets.QLabel(self.actualiza_producto)
        self.label_22.setGeometry(QtCore.QRect(560, 200, 51, 31))
        self.label_22.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"")
        self.label_22.setObjectName("label_22")
        self.label_23 = QtWidgets.QLabel(self.actualiza_producto)
        self.label_23.setGeometry(QtCore.QRect(560, 270, 51, 31))
        self.label_23.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"")
        self.label_23.setObjectName("label_23")
        self.label_24 = QtWidgets.QLabel(self.actualiza_producto)
        self.label_24.setGeometry(QtCore.QRect(560, 340, 71, 31))
        self.label_24.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"")
        self.label_24.setObjectName("label_24")
        self.btn_actualizar_producto = QtWidgets.QPushButton(self.actualiza_producto)
        self.btn_actualizar_producto.setGeometry(QtCore.QRect(890, 430, 101, 41))
        self.btn_actualizar_producto.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_actualizar_producto.setObjectName("btn_actualizar_producto")
        self.txt_actualiza_cod_producto = QtWidgets.QLineEdit(self.actualiza_producto)
        self.txt_actualiza_cod_producto.setEnabled(False)
        self.txt_actualiza_cod_producto.setGeometry(QtCore.QRect(660, 60, 71, 31))
        self.txt_actualiza_cod_producto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_actualiza_cod_producto.setObjectName("txt_actualiza_cod_producto")
        self.txt_actualiza_precio_producto = QtWidgets.QLineEdit(self.actualiza_producto)
        self.txt_actualiza_precio_producto.setGeometry(QtCore.QRect(660, 270, 121, 31))
        self.txt_actualiza_precio_producto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_actualiza_precio_producto.setObjectName("txt_actualiza_precio_producto")
        self.txt_actualiza_marca_producto = QtWidgets.QLineEdit(self.actualiza_producto)
        self.txt_actualiza_marca_producto.setGeometry(QtCore.QRect(660, 200, 111, 31))
        self.txt_actualiza_marca_producto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_actualiza_marca_producto.setObjectName("txt_actualiza_marca_producto")
        self.txt_actualiza_tipo_producto = QtWidgets.QLineEdit(self.actualiza_producto)
        self.txt_actualiza_tipo_producto.setGeometry(QtCore.QRect(660, 130, 111, 31))
        self.txt_actualiza_tipo_producto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_actualiza_tipo_producto.setObjectName("txt_actualiza_tipo_producto")
        self.txt_actualiza_cantidad_producto = QtWidgets.QLineEdit(self.actualiza_producto)
        self.txt_actualiza_cantidad_producto.setGeometry(QtCore.QRect(660, 340, 121, 31))
        self.txt_actualiza_cantidad_producto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_actualiza_cantidad_producto.setObjectName("txt_actualiza_cantidad_producto")
        self.label_41 = QtWidgets.QLabel(self.actualiza_producto)
        self.label_41.setGeometry(QtCore.QRect(130, 30, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_41.setObjectName("label_41")
        self.btn_actualizar_producto_limpia = QtWidgets.QPushButton(self.actualiza_producto)
        self.btn_actualizar_producto_limpia.setGeometry(QtCore.QRect(890, 310, 101, 31))
        self.btn_actualizar_producto_limpia.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_actualizar_producto_limpia.setObjectName("btn_actualizar_producto_limpia")
        self.txt_busca_actualiza_producto = QtWidgets.QLineEdit(self.actualiza_producto)
        self.txt_busca_actualiza_producto.setGeometry(QtCore.QRect(250, 90, 161, 31))
        self.txt_busca_actualiza_producto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_busca_actualiza_producto.setObjectName("txt_busca_actualiza_producto")
        self.label_60 = QtWidgets.QLabel(self.actualiza_producto)
        self.label_60.setGeometry(QtCore.QRect(120, 90, 61, 31))
        self.label_60.setObjectName("label_60")
        self.contenedor_paginas.addWidget(self.actualiza_producto)
        self.elimina_cliente = QtWidgets.QWidget()
        self.elimina_cliente.setObjectName("elimina_cliente")
        self.tabla_elimina_cliente = QtWidgets.QTableWidget(self.elimina_cliente)
        self.tabla_elimina_cliente.setGeometry(QtCore.QRect(30, 150, 511, 351))
        self.tabla_elimina_cliente.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.tabla_elimina_cliente.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabla_elimina_cliente.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_elimina_cliente.setObjectName("tabla_elimina_cliente")
        self.tabla_elimina_cliente.setColumnCount(5)
        self.tabla_elimina_cliente.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_elimina_cliente.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_elimina_cliente.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_elimina_cliente.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_elimina_cliente.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_elimina_cliente.setHorizontalHeaderItem(4, item)
        self.label_25 = QtWidgets.QLabel(self.elimina_cliente)
        self.label_25.setGeometry(QtCore.QRect(560, 70, 81, 31))
        self.label_25.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(self.elimina_cliente)
        self.label_26.setGeometry(QtCore.QRect(560, 130, 61, 31))
        self.label_26.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(self.elimina_cliente)
        self.label_27.setGeometry(QtCore.QRect(560, 200, 41, 31))
        self.label_27.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_27.setObjectName("label_27")
        self.label_28 = QtWidgets.QLabel(self.elimina_cliente)
        self.label_28.setGeometry(QtCore.QRect(560, 270, 61, 31))
        self.label_28.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_28.setObjectName("label_28")
        self.label_29 = QtWidgets.QLabel(self.elimina_cliente)
        self.label_29.setGeometry(QtCore.QRect(560, 340, 51, 31))
        self.label_29.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_29.setObjectName("label_29")
        self.txt_elimina_cod_cliente = QtWidgets.QLineEdit(self.elimina_cliente)
        self.txt_elimina_cod_cliente.setEnabled(False)
        self.txt_elimina_cod_cliente.setGeometry(QtCore.QRect(660, 70, 71, 31))
        self.txt_elimina_cod_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_elimina_cod_cliente.setObjectName("txt_elimina_cod_cliente")
        self.txt_elimina_nombre_cliente = QtWidgets.QLineEdit(self.elimina_cliente)
        self.txt_elimina_nombre_cliente.setGeometry(QtCore.QRect(660, 130, 131, 31))
        self.txt_elimina_nombre_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_elimina_nombre_cliente.setObjectName("txt_elimina_nombre_cliente")
        self.txt_elimina_dni = QtWidgets.QLineEdit(self.elimina_cliente)
        self.txt_elimina_dni.setGeometry(QtCore.QRect(660, 200, 131, 31))
        self.txt_elimina_dni.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_elimina_dni.setObjectName("txt_elimina_dni")
        self.txt_elimina_telefono = QtWidgets.QLineEdit(self.elimina_cliente)
        self.txt_elimina_telefono.setGeometry(QtCore.QRect(660, 270, 131, 31))
        self.txt_elimina_telefono.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_elimina_telefono.setObjectName("txt_elimina_telefono")
        self.cmb_elimina_sexo = QtWidgets.QComboBox(self.elimina_cliente)
        self.cmb_elimina_sexo.setGeometry(QtCore.QRect(660, 340, 131, 31))
        self.cmb_elimina_sexo.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmb_elimina_sexo.setObjectName("cmb_elimina_sexo")
        self.cmb_elimina_sexo.addItem("")
        self.cmb_elimina_sexo.setItemText(0, "")
        self.cmb_elimina_sexo.addItem("")
        self.cmb_elimina_sexo.addItem("")
        self.btn_elimina_cliente = QtWidgets.QPushButton(self.elimina_cliente)
        self.btn_elimina_cliente.setGeometry(QtCore.QRect(880, 440, 91, 41))
        self.btn_elimina_cliente.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_elimina_cliente.setObjectName("btn_elimina_cliente")
        self.label_42 = QtWidgets.QLabel(self.elimina_cliente)
        self.label_42.setGeometry(QtCore.QRect(170, 30, 211, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_42.setObjectName("label_42")
        self.btn_elimina_cliente_limpia = QtWidgets.QPushButton(self.elimina_cliente)
        self.btn_elimina_cliente_limpia.setGeometry(QtCore.QRect(880, 340, 101, 31))
        self.btn_elimina_cliente_limpia.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_elimina_cliente_limpia.setObjectName("btn_elimina_cliente_limpia")
        self.label_61 = QtWidgets.QLabel(self.elimina_cliente)
        self.label_61.setGeometry(QtCore.QRect(160, 90, 61, 31))
        self.label_61.setObjectName("label_61")
        self.txt_busca_elimina_cliente = QtWidgets.QLineEdit(self.elimina_cliente)
        self.txt_busca_elimina_cliente.setGeometry(QtCore.QRect(250, 90, 161, 31))
        self.txt_busca_elimina_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_busca_elimina_cliente.setObjectName("txt_busca_elimina_cliente")
        self.contenedor_paginas.addWidget(self.elimina_cliente)
        self.elimina_producto = QtWidgets.QWidget()
        self.elimina_producto.setObjectName("elimina_producto")
        self.tabla_elimina_producto = QtWidgets.QTableWidget(self.elimina_producto)
        self.tabla_elimina_producto.setGeometry(QtCore.QRect(30, 160, 501, 341))
        self.tabla_elimina_producto.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.tabla_elimina_producto.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabla_elimina_producto.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_elimina_producto.setObjectName("tabla_elimina_producto")
        self.tabla_elimina_producto.setColumnCount(5)
        self.tabla_elimina_producto.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_elimina_producto.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_elimina_producto.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_elimina_producto.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_elimina_producto.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_elimina_producto.setHorizontalHeaderItem(4, item)
        self.label_30 = QtWidgets.QLabel(self.elimina_producto)
        self.label_30.setGeometry(QtCore.QRect(570, 100, 101, 31))
        self.label_30.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_30.setObjectName("label_30")
        self.label_31 = QtWidgets.QLabel(self.elimina_producto)
        self.label_31.setGeometry(QtCore.QRect(570, 170, 41, 31))
        self.label_31.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_31.setObjectName("label_31")
        self.label_32 = QtWidgets.QLabel(self.elimina_producto)
        self.label_32.setGeometry(QtCore.QRect(570, 240, 51, 31))
        self.label_32.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_32.setObjectName("label_32")
        self.label_33 = QtWidgets.QLabel(self.elimina_producto)
        self.label_33.setGeometry(QtCore.QRect(570, 310, 51, 31))
        self.label_33.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_33.setObjectName("label_33")
        self.label_34 = QtWidgets.QLabel(self.elimina_producto)
        self.label_34.setGeometry(QtCore.QRect(570, 380, 61, 31))
        self.label_34.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_34.setObjectName("label_34")
        self.txt_elimina_cod_producto = QtWidgets.QLineEdit(self.elimina_producto)
        self.txt_elimina_cod_producto.setEnabled(False)
        self.txt_elimina_cod_producto.setGeometry(QtCore.QRect(690, 100, 71, 31))
        self.txt_elimina_cod_producto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_elimina_cod_producto.setObjectName("txt_elimina_cod_producto")
        self.txt_elimina_tipo_producto = QtWidgets.QLineEdit(self.elimina_producto)
        self.txt_elimina_tipo_producto.setGeometry(QtCore.QRect(690, 170, 111, 31))
        self.txt_elimina_tipo_producto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_elimina_tipo_producto.setObjectName("txt_elimina_tipo_producto")
        self.txt_elimina_marca_producto = QtWidgets.QLineEdit(self.elimina_producto)
        self.txt_elimina_marca_producto.setGeometry(QtCore.QRect(690, 240, 111, 31))
        self.txt_elimina_marca_producto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_elimina_marca_producto.setObjectName("txt_elimina_marca_producto")
        self.txt_elimina_precio_producto = QtWidgets.QLineEdit(self.elimina_producto)
        self.txt_elimina_precio_producto.setGeometry(QtCore.QRect(690, 310, 111, 31))
        self.txt_elimina_precio_producto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_elimina_precio_producto.setObjectName("txt_elimina_precio_producto")
        self.txt_elimina_cantidad_producto = QtWidgets.QLineEdit(self.elimina_producto)
        self.txt_elimina_cantidad_producto.setGeometry(QtCore.QRect(690, 380, 111, 31))
        self.txt_elimina_cantidad_producto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_elimina_cantidad_producto.setObjectName("txt_elimina_cantidad_producto")
        self.btn_elimina_producto = QtWidgets.QPushButton(self.elimina_producto)
        self.btn_elimina_producto.setGeometry(QtCore.QRect(880, 440, 101, 41))
        self.btn_elimina_producto.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_elimina_producto.setObjectName("btn_elimina_producto")
        self.label_44 = QtWidgets.QLabel(self.elimina_producto)
        self.label_44.setGeometry(QtCore.QRect(150, 40, 241, 27))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_44.setObjectName("label_44")
        self.btn_elimina_producto_limpia = QtWidgets.QPushButton(self.elimina_producto)
        self.btn_elimina_producto_limpia.setGeometry(QtCore.QRect(880, 340, 101, 31))
        self.btn_elimina_producto_limpia.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_elimina_producto_limpia.setObjectName("btn_elimina_producto_limpia")
        self.label_62 = QtWidgets.QLabel(self.elimina_producto)
        self.label_62.setGeometry(QtCore.QRect(140, 100, 61, 31))
        self.label_62.setObjectName("label_62")
        self.txt_busca_elimina_producto = QtWidgets.QLineEdit(self.elimina_producto)
        self.txt_busca_elimina_producto.setGeometry(QtCore.QRect(260, 100, 161, 31))
        self.txt_busca_elimina_producto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_busca_elimina_producto.setObjectName("txt_busca_elimina_producto")
        self.contenedor_paginas.addWidget(self.elimina_producto)
        self.venta_general = QtWidgets.QWidget()
        self.venta_general.setObjectName("venta_general")
        self.label_47 = QtWidgets.QLabel(self.venta_general)
        self.label_47.setGeometry(QtCore.QRect(420, 20, 191, 27))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_47.setObjectName("label_47")
        self.btn_agregar_lista_venta = QtWidgets.QPushButton(self.venta_general)
        self.btn_agregar_lista_venta.setGeometry(QtCore.QRect(930, 200, 101, 41))
        self.btn_agregar_lista_venta.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_agregar_lista_venta.setObjectName("btn_agregar_lista_venta")
        self.label = QtWidgets.QLabel(self.venta_general)
        self.label.setGeometry(QtCore.QRect(10, 40, 91, 21))
        self.label.setObjectName("label")
        self.cod_cliente_venta = QtWidgets.QLineEdit(self.venta_general)
        self.cod_cliente_venta.setEnabled(False)
        self.cod_cliente_venta.setGeometry(QtCore.QRect(660, 80, 71, 31))
        self.cod_cliente_venta.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cod_cliente_venta.setObjectName("cod_cliente_venta")
        self.tabla_lista_venta = QtWidgets.QTableWidget(self.venta_general)
        self.tabla_lista_venta.setGeometry(QtCore.QRect(580, 250, 421, 221))
        self.tabla_lista_venta.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabla_lista_venta.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabla_lista_venta.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_lista_venta.setObjectName("tabla_lista_venta")
        self.tabla_lista_venta.setColumnCount(4)
        self.tabla_lista_venta.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_lista_venta.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_lista_venta.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_lista_venta.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_lista_venta.setHorizontalHeaderItem(3, item)
        self.label_48 = QtWidgets.QLabel(self.venta_general)
        self.label_48.setGeometry(QtCore.QRect(10, 280, 101, 21))
        self.label_48.setObjectName("label_48")
        self.label_49 = QtWidgets.QLabel(self.venta_general)
        self.label_49.setGeometry(QtCore.QRect(560, 80, 81, 31))
        self.label_49.setObjectName("label_49")
        self.label_98 = QtWidgets.QLabel(self.venta_general)
        self.label_98.setGeometry(QtCore.QRect(580, 130, 61, 31))
        self.label_98.setObjectName("label_98")
        self.nombre_cliente_venta = QtWidgets.QLineEdit(self.venta_general)
        self.nombre_cliente_venta.setEnabled(False)
        self.nombre_cliente_venta.setGeometry(QtCore.QRect(660, 130, 121, 31))
        self.nombre_cliente_venta.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.nombre_cliente_venta.setObjectName("nombre_cliente_venta")
        self.label_99 = QtWidgets.QLabel(self.venta_general)
        self.label_99.setGeometry(QtCore.QRect(800, 80, 101, 31))
        self.label_99.setObjectName("label_99")
        self.label_100 = QtWidgets.QLabel(self.venta_general)
        self.label_100.setGeometry(QtCore.QRect(800, 130, 61, 31))
        self.label_100.setObjectName("label_100")
        self.cod_producto_venta = QtWidgets.QLineEdit(self.venta_general)
        self.cod_producto_venta.setEnabled(False)
        self.cod_producto_venta.setGeometry(QtCore.QRect(920, 80, 71, 31))
        self.cod_producto_venta.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cod_producto_venta.setObjectName("cod_producto_venta")
        self.tipo_producto_venta = QtWidgets.QLineEdit(self.venta_general)
        self.tipo_producto_venta.setEnabled(False)
        self.tipo_producto_venta.setGeometry(QtCore.QRect(920, 130, 121, 31))
        self.tipo_producto_venta.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tipo_producto_venta.setObjectName("tipo_producto_venta")
        self.label_101 = QtWidgets.QLabel(self.venta_general)
        self.label_101.setGeometry(QtCore.QRect(570, 180, 71, 31))
        self.label_101.setObjectName("label_101")
        self.cantida_producto_venta = QtWidgets.QLineEdit(self.venta_general)
        self.cantida_producto_venta.setGeometry(QtCore.QRect(660, 180, 71, 31))
        self.cantida_producto_venta.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cantida_producto_venta.setObjectName("cantida_producto_venta")
        self.btn_registrar_venta = QtWidgets.QPushButton(self.venta_general)
        self.btn_registrar_venta.setGeometry(QtCore.QRect(940, 480, 111, 41))
        self.btn_registrar_venta.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_registrar_venta.setObjectName("btn_registrar_venta")
        self.tabla_cliente_venta = QtWidgets.QTableWidget(self.venta_general)
        self.tabla_cliente_venta.setGeometry(QtCore.QRect(10, 70, 501, 181))
        self.tabla_cliente_venta.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.tabla_cliente_venta.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabla_cliente_venta.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_cliente_venta.setObjectName("tabla_cliente_venta")
        self.tabla_cliente_venta.setColumnCount(5)
        self.tabla_cliente_venta.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_cliente_venta.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_cliente_venta.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_cliente_venta.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_cliente_venta.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_cliente_venta.setHorizontalHeaderItem(4, item)
        self.tabla_producto_venta = QtWidgets.QTableWidget(self.venta_general)
        self.tabla_producto_venta.setGeometry(QtCore.QRect(10, 310, 501, 211))
        self.tabla_producto_venta.setStyleSheet("background-color: rgb(255, 255, 127);\n"
"background-color: rgb(255, 255, 255);")
        self.tabla_producto_venta.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabla_producto_venta.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_producto_venta.setObjectName("tabla_producto_venta")
        self.tabla_producto_venta.setColumnCount(5)
        self.tabla_producto_venta.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_venta.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_venta.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_venta.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_venta.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_producto_venta.setHorizontalHeaderItem(4, item)
        self.btn_venta_limpia_tabla = QtWidgets.QPushButton(self.venta_general)
        self.btn_venta_limpia_tabla.setGeometry(QtCore.QRect(580, 480, 101, 41))
        self.btn_venta_limpia_tabla.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_venta_limpia_tabla.setObjectName("btn_venta_limpia_tabla")
        self.btn_venta_limpia_datos = QtWidgets.QPushButton(self.venta_general)
        self.btn_venta_limpia_datos.setGeometry(QtCore.QRect(930, 20, 101, 41))
        self.btn_venta_limpia_datos.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_venta_limpia_datos.setObjectName("btn_venta_limpia_datos")
        self.label_55 = QtWidgets.QLabel(self.venta_general)
        self.label_55.setGeometry(QtCore.QRect(250, 20, 71, 31))
        self.label_55.setObjectName("label_55")
        self.num_venta = QtWidgets.QLineEdit(self.venta_general)
        self.num_venta.setEnabled(False)
        self.num_venta.setGeometry(QtCore.QRect(330, 20, 71, 31))
        self.num_venta.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.num_venta.setObjectName("num_venta")
        self.label_56 = QtWidgets.QLabel(self.venta_general)
        self.label_56.setGeometry(QtCore.QRect(640, 20, 51, 31))
        self.label_56.setObjectName("label_56")
        self.fecha_venta = QtWidgets.QLineEdit(self.venta_general)
        self.fecha_venta.setEnabled(False)
        self.fecha_venta.setGeometry(QtCore.QRect(720, 20, 101, 31))
        self.fecha_venta.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.fecha_venta.setObjectName("fecha_venta")
        self.txt_busca_venta_cliente = QtWidgets.QLineEdit(self.venta_general)
        self.txt_busca_venta_cliente.setGeometry(QtCore.QRect(110, 30, 121, 31))
        self.txt_busca_venta_cliente.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_busca_venta_cliente.setObjectName("txt_busca_venta_cliente")
        self.txt_busca_venta_producto = QtWidgets.QLineEdit(self.venta_general)
        self.txt_busca_venta_producto.setGeometry(QtCore.QRect(120, 270, 121, 31))
        self.txt_busca_venta_producto.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.txt_busca_venta_producto.setObjectName("txt_busca_venta_producto")
        self.contenedor_paginas.addWidget(self.venta_general)
        self.ingresa_fecha_mensual = QtWidgets.QWidget()
        self.ingresa_fecha_mensual.setObjectName("ingresa_fecha_mensual")
        self.btn_calcula_reporte_mensual = QtWidgets.QPushButton(self.ingresa_fecha_mensual)
        self.btn_calcula_reporte_mensual.setGeometry(QtCore.QRect(610, 340, 161, 51))
        self.btn_calcula_reporte_mensual.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_calcula_reporte_mensual.setObjectName("btn_calcula_reporte_mensual")
        self.label_2 = QtWidgets.QLabel(self.ingresa_fecha_mensual)
        self.label_2.setGeometry(QtCore.QRect(290, 30, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.ingresa_fecha_mensual)
        self.label_3.setGeometry(QtCore.QRect(550, 170, 51, 31))
        self.label_3.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"")
        self.label_3.setObjectName("label_3")
        self.cmb_meses_reporte_mensual = QtWidgets.QComboBox(self.ingresa_fecha_mensual)
        self.cmb_meses_reporte_mensual.setGeometry(QtCore.QRect(550, 240, 131, 31))
        self.cmb_meses_reporte_mensual.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmb_meses_reporte_mensual.setObjectName("cmb_meses_reporte_mensual")
        self.cmb_meses_reporte_mensual.addItem("")
        self.cmb_meses_reporte_mensual.setItemText(0, "")
        self.cmb_meses_reporte_mensual.addItem("")
        self.cmb_meses_reporte_mensual.addItem("")
        self.cmb_meses_reporte_mensual.addItem("")
        self.cmb_meses_reporte_mensual.addItem("")
        self.cmb_meses_reporte_mensual.addItem("")
        self.cmb_meses_reporte_mensual.addItem("")
        self.cmb_meses_reporte_mensual.addItem("")
        self.cmb_meses_reporte_mensual.addItem("")
        self.cmb_meses_reporte_mensual.addItem("")
        self.cmb_meses_reporte_mensual.addItem("")
        self.cmb_meses_reporte_mensual.addItem("")
        self.cmb_meses_reporte_mensual.addItem("")
        self.cmb_reporte_mensual_anio = QtWidgets.QComboBox(self.ingresa_fecha_mensual)
        self.cmb_reporte_mensual_anio.setGeometry(QtCore.QRect(340, 240, 141, 31))
        self.cmb_reporte_mensual_anio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmb_reporte_mensual_anio.setObjectName("cmb_reporte_mensual_anio")
        self.cmb_reporte_mensual_anio.addItem("")
        self.cmb_reporte_mensual_anio.setItemText(0, "")
        self.cmb_reporte_mensual_anio.addItem("")
        self.cmb_reporte_mensual_anio.addItem("")
        self.cmb_reporte_mensual_anio.addItem("")
        self.label_52 = QtWidgets.QLabel(self.ingresa_fecha_mensual)
        self.label_52.setGeometry(QtCore.QRect(340, 170, 51, 31))
        self.label_52.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"")
        self.label_52.setObjectName("label_52")
        self.btn_reporte_mensual_limpiar = QtWidgets.QPushButton(self.ingresa_fecha_mensual)
        self.btn_reporte_mensual_limpiar.setGeometry(QtCore.QRect(760, 230, 111, 41))
        self.btn_reporte_mensual_limpiar.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_reporte_mensual_limpiar.setObjectName("btn_reporte_mensual_limpiar")
        self.contenedor_paginas.addWidget(self.ingresa_fecha_mensual)
        self.reporte_mensual = QtWidgets.QWidget()
        self.reporte_mensual.setObjectName("reporte_mensual")
        self.btn_volver_mensual = QtWidgets.QPushButton(self.reporte_mensual)
        self.btn_volver_mensual.setGeometry(QtCore.QRect(840, 450, 111, 31))
        self.btn_volver_mensual.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_volver_mensual.setObjectName("btn_volver_mensual")
        self.tabla_reporte_mensual = QtWidgets.QTableWidget(self.reporte_mensual)
        self.tabla_reporte_mensual.setGeometry(QtCore.QRect(280, 100, 431, 391))
        self.tabla_reporte_mensual.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabla_reporte_mensual.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabla_reporte_mensual.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_reporte_mensual.setObjectName("tabla_reporte_mensual")
        self.tabla_reporte_mensual.setColumnCount(4)
        self.tabla_reporte_mensual.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_reporte_mensual.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_reporte_mensual.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_reporte_mensual.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_reporte_mensual.setHorizontalHeaderItem(3, item)
        self.label_45 = QtWidgets.QLabel(self.reporte_mensual)
        self.label_45.setGeometry(QtCore.QRect(380, 40, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_45.setObjectName("label_45")
        self.btn_pdf_mensual = QtWidgets.QPushButton(self.reporte_mensual)
        self.btn_pdf_mensual.setGeometry(QtCore.QRect(840, 260, 111, 41))
        self.btn_pdf_mensual.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_pdf_mensual.setObjectName("btn_pdf_mensual")
        self.contenedor_paginas.addWidget(self.reporte_mensual)
        self.ingresa_fecha_semanal = QtWidgets.QWidget()
        self.ingresa_fecha_semanal.setObjectName("ingresa_fecha_semanal")
        self.label_4 = QtWidgets.QLabel(self.ingresa_fecha_semanal)
        self.label_4.setGeometry(QtCore.QRect(260, 30, 491, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"")
        self.label_4.setObjectName("label_4")
        self.label_35 = QtWidgets.QLabel(self.ingresa_fecha_semanal)
        self.label_35.setGeometry(QtCore.QRect(470, 120, 51, 31))
        self.label_35.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"")
        self.label_35.setObjectName("label_35")
        self.btn_calcular_semanal = QtWidgets.QPushButton(self.ingresa_fecha_semanal)
        self.btn_calcular_semanal.setGeometry(QtCore.QRect(630, 350, 121, 51))
        self.btn_calcular_semanal.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_calcular_semanal.setObjectName("btn_calcular_semanal")
        self.cmb_semanas_reporte_semanal = QtWidgets.QComboBox(self.ingresa_fecha_semanal)
        self.cmb_semanas_reporte_semanal.setGeometry(QtCore.QRect(680, 190, 131, 31))
        self.cmb_semanas_reporte_semanal.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmb_semanas_reporte_semanal.setObjectName("cmb_semanas_reporte_semanal")
        self.cmb_semanas_reporte_semanal.addItem("")
        self.cmb_semanas_reporte_semanal.setItemText(0, "")
        self.cmb_semanas_reporte_semanal.addItem("")
        self.cmb_semanas_reporte_semanal.addItem("")
        self.cmb_semanas_reporte_semanal.addItem("")
        self.cmb_semanas_reporte_semanal.addItem("")
        self.cmb_meses_reporte_semanal = QtWidgets.QComboBox(self.ingresa_fecha_semanal)
        self.cmb_meses_reporte_semanal.setGeometry(QtCore.QRect(470, 190, 131, 31))
        self.cmb_meses_reporte_semanal.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmb_meses_reporte_semanal.setObjectName("cmb_meses_reporte_semanal")
        self.cmb_meses_reporte_semanal.addItem("")
        self.cmb_meses_reporte_semanal.setItemText(0, "")
        self.cmb_meses_reporte_semanal.addItem("")
        self.cmb_meses_reporte_semanal.addItem("")
        self.cmb_meses_reporte_semanal.addItem("")
        self.cmb_meses_reporte_semanal.addItem("")
        self.cmb_meses_reporte_semanal.addItem("")
        self.cmb_meses_reporte_semanal.addItem("")
        self.cmb_meses_reporte_semanal.addItem("")
        self.cmb_meses_reporte_semanal.addItem("")
        self.cmb_meses_reporte_semanal.addItem("")
        self.cmb_meses_reporte_semanal.addItem("")
        self.cmb_meses_reporte_semanal.addItem("")
        self.cmb_meses_reporte_semanal.addItem("")
        self.label_51 = QtWidgets.QLabel(self.ingresa_fecha_semanal)
        self.label_51.setGeometry(QtCore.QRect(680, 120, 51, 31))
        self.label_51.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"")
        self.label_51.setObjectName("label_51")
        self.cmb_reporte_semanal_anio = QtWidgets.QComboBox(self.ingresa_fecha_semanal)
        self.cmb_reporte_semanal_anio.setGeometry(QtCore.QRect(260, 190, 141, 31))
        self.cmb_reporte_semanal_anio.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.cmb_reporte_semanal_anio.setObjectName("cmb_reporte_semanal_anio")
        self.cmb_reporte_semanal_anio.addItem("")
        self.cmb_reporte_semanal_anio.setItemText(0, "")
        self.cmb_reporte_semanal_anio.addItem("")
        self.cmb_reporte_semanal_anio.addItem("")
        self.cmb_reporte_semanal_anio.addItem("")
        self.label_53 = QtWidgets.QLabel(self.ingresa_fecha_semanal)
        self.label_53.setGeometry(QtCore.QRect(260, 120, 51, 31))
        self.label_53.setStyleSheet("background-color: rgb(128, 128, 128);\n"
"")
        self.label_53.setObjectName("label_53")
        self.btn_reporte_semanal_limpiar = QtWidgets.QPushButton(self.ingresa_fecha_semanal)
        self.btn_reporte_semanal_limpiar.setGeometry(QtCore.QRect(320, 350, 111, 41))
        self.btn_reporte_semanal_limpiar.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_reporte_semanal_limpiar.setObjectName("btn_reporte_semanal_limpiar")
        self.contenedor_paginas.addWidget(self.ingresa_fecha_semanal)
        self.reporte_semanal = QtWidgets.QWidget()
        self.reporte_semanal.setObjectName("reporte_semanal")
        self.tabla_reporte_semanal = QtWidgets.QTableWidget(self.reporte_semanal)
        self.tabla_reporte_semanal.setGeometry(QtCore.QRect(300, 120, 431, 381))
        self.tabla_reporte_semanal.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.tabla_reporte_semanal.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tabla_reporte_semanal.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tabla_reporte_semanal.setObjectName("tabla_reporte_semanal")
        self.tabla_reporte_semanal.setColumnCount(4)
        self.tabla_reporte_semanal.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_reporte_semanal.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_reporte_semanal.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_reporte_semanal.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tabla_reporte_semanal.setHorizontalHeaderItem(3, item)
        self.btn_volver_semanal = QtWidgets.QPushButton(self.reporte_semanal)
        self.btn_volver_semanal.setGeometry(QtCore.QRect(820, 440, 141, 41))
        self.btn_volver_semanal.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_volver_semanal.setObjectName("btn_volver_semanal")
        self.label_46 = QtWidgets.QLabel(self.reporte_semanal)
        self.label_46.setGeometry(QtCore.QRect(380, 60, 221, 27))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet("background-color: rgb(128, 128, 128);")
        self.label_46.setObjectName("label_46")
        self.btn_pdf_semanal = QtWidgets.QPushButton(self.reporte_semanal)
        self.btn_pdf_semanal.setGeometry(QtCore.QRect(830, 300, 111, 41))
        self.btn_pdf_semanal.setStyleSheet("background-color: rgb(20, 113, 134);")
        self.btn_pdf_semanal.setObjectName("btn_pdf_semanal")
        self.contenedor_paginas.addWidget(self.reporte_semanal)
        self.horizontalLayout_3.addWidget(self.contenedor_paginas)
        self.horizontalLayout_2.addWidget(self.vista)
        self.verticalLayout.addWidget(self.contenido)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 8)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.contenedor_paginas.setCurrentIndex(13)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_43.setText(_translate("MainWindow", "SISTEMA DE VENTA"))
        self.rbtn_cliente.setText(_translate("MainWindow", "CLIENTE"))
        self.rbtn_producto.setText(_translate("MainWindow", "PRODUCTO"))
        self.btn_base_datos.setText(_translate("MainWindow", "BASE DE DATOS"))
        self.btn_registrar.setText(_translate("MainWindow", "REGISTRAR"))
        self.btn_actualizar.setText(_translate("MainWindow", "ACTUALIZAR"))
        self.btn_eliminar.setText(_translate("MainWindow", "ELIMINAR"))
        self.btn_reporte_mensual.setText(_translate("MainWindow", "REPORTE DE VENTAS\n"
"MENSUAL"))
        self.btn_reporte_semanal.setText(_translate("MainWindow", "REPORTE DE VENTAS\n"
"SEMANAL"))
        self.btn_venta.setText(_translate("MainWindow", "VENTA"))
        self.label_54.setText(_translate("MainWindow", "LGD TECHNOLOGIES"))
        item = self.tabla_cliente.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "COD_CLIENTE"))
        item = self.tabla_cliente.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOMBRE"))
        item = self.tabla_cliente.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DNI"))
        item = self.tabla_cliente.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "TELEFONO"))
        item = self.tabla_cliente.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "SEXO"))
        self.label_36.setText(_translate("MainWindow", "BASE DE DATOS DE CLIENTE"))
        self.label_57.setText(_translate("MainWindow", "BUSCAR"))
        item = self.tabla_producto.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "COD_PRODUCTO"))
        item = self.tabla_producto.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TIPO"))
        item = self.tabla_producto.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "MARCA"))
        item = self.tabla_producto.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "PRECIO"))
        item = self.tabla_producto.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "CANTIDAD"))
        self.label_37.setText(_translate("MainWindow", "BASE DE DATOS DE PRODUCTOS"))
        self.label_58.setText(_translate("MainWindow", "BUSCAR"))
        self.label_5.setText(_translate("MainWindow", "COD_CLIENTE"))
        self.label_6.setText(_translate("MainWindow", "NOMBRE"))
        self.label_7.setText(_translate("MainWindow", "DNI"))
        self.label_8.setText(_translate("MainWindow", "TELEFONO"))
        self.label_9.setText(_translate("MainWindow", "SEXO"))
        self.cmb_sexo_cliente.setItemText(1, _translate("MainWindow", "MASCULINO"))
        self.cmb_sexo_cliente.setItemText(2, _translate("MainWindow", "FEMENINO"))
        self.btn_limpiar_cliente.setText(_translate("MainWindow", "LIMPIAR"))
        self.btn_registrar_cliente.setText(_translate("MainWindow", "REGISTRAR"))
        self.label_38.setText(_translate("MainWindow", "REGISTRO DE CLIENTE"))
        self.label_10.setText(_translate("MainWindow", "COD_PRODUCTO"))
        self.label_11.setText(_translate("MainWindow", "CANTIDAD"))
        self.label_12.setText(_translate("MainWindow", "PRECIO"))
        self.label_13.setText(_translate("MainWindow", "MARCA"))
        self.label_14.setText(_translate("MainWindow", "TIPO"))
        self.btn_limpiar_producto.setText(_translate("MainWindow", "LIMPIAR"))
        self.btn_registar_producto.setText(_translate("MainWindow", "REGISTRAR"))
        self.label_39.setText(_translate("MainWindow", "REGISTRO PRODUCTOS"))
        item = self.tabla_actualiza_cliente.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "COD_CLIENTE"))
        item = self.tabla_actualiza_cliente.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOMBRE"))
        item = self.tabla_actualiza_cliente.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DNI"))
        item = self.tabla_actualiza_cliente.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "TELEFONO"))
        item = self.tabla_actualiza_cliente.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "SEXO"))
        self.btn_actualizar_cliente.setText(_translate("MainWindow", "ACTUALIZAR"))
        self.label_15.setText(_translate("MainWindow", "COD_CLIENTE"))
        self.label_16.setText(_translate("MainWindow", "NOMBRE"))
        self.label_17.setText(_translate("MainWindow", "DNI"))
        self.label_18.setText(_translate("MainWindow", "SEXO"))
        self.label_19.setText(_translate("MainWindow", "TELEFONO"))
        self.cmb_actualiza_sexo.setItemText(1, _translate("MainWindow", "MASCULINO"))
        self.cmb_actualiza_sexo.setItemText(2, _translate("MainWindow", "FEMENINO"))
        self.label_40.setText(_translate("MainWindow", "ACTUALIZAR CLIENTE"))
        self.btn_actualizar_cliente_limpia.setText(_translate("MainWindow", "LIMPIAR"))
        self.label_59.setText(_translate("MainWindow", "BUSCAR"))
        item = self.tabla_actualiza_producto.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "COD_PRODUCTO"))
        item = self.tabla_actualiza_producto.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TIPO"))
        item = self.tabla_actualiza_producto.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "MARCA"))
        item = self.tabla_actualiza_producto.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "PRECIO"))
        item = self.tabla_actualiza_producto.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "CANTIDAD"))
        self.label_20.setText(_translate("MainWindow", "COD_PRODUCTO"))
        self.label_21.setText(_translate("MainWindow", "TIPO"))
        self.label_22.setText(_translate("MainWindow", "MARCA"))
        self.label_23.setText(_translate("MainWindow", "PRECIO"))
        self.label_24.setText(_translate("MainWindow", "CANTIDAD"))
        self.btn_actualizar_producto.setText(_translate("MainWindow", "ACTUALIZAR"))
        self.label_41.setText(_translate("MainWindow", "ACTUALIZAR PRODUCTO"))
        self.btn_actualizar_producto_limpia.setText(_translate("MainWindow", "LIMPIAR"))
        self.label_60.setText(_translate("MainWindow", "BUSCAR"))
        item = self.tabla_elimina_cliente.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "COD_CLIENTE"))
        item = self.tabla_elimina_cliente.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOMBRE"))
        item = self.tabla_elimina_cliente.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DNI"))
        item = self.tabla_elimina_cliente.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "TELEFONO"))
        item = self.tabla_elimina_cliente.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "SEXO"))
        self.label_25.setText(_translate("MainWindow", "COD_CLIENTE"))
        self.label_26.setText(_translate("MainWindow", "NOMBRE"))
        self.label_27.setText(_translate("MainWindow", "DNI"))
        self.label_28.setText(_translate("MainWindow", "TELEFONO"))
        self.label_29.setText(_translate("MainWindow", "SEXO"))
        self.cmb_elimina_sexo.setItemText(1, _translate("MainWindow", "MASCULINO"))
        self.cmb_elimina_sexo.setItemText(2, _translate("MainWindow", "FEMENINO"))
        self.btn_elimina_cliente.setText(_translate("MainWindow", "ELIMINAR"))
        self.label_42.setText(_translate("MainWindow", "ELIMINA CLIENTE"))
        self.btn_elimina_cliente_limpia.setText(_translate("MainWindow", "LIMPIAR"))
        self.label_61.setText(_translate("MainWindow", "BUSCAR"))
        item = self.tabla_elimina_producto.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "COD_PRODUCTO"))
        item = self.tabla_elimina_producto.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TIPO"))
        item = self.tabla_elimina_producto.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "MARCA"))
        item = self.tabla_elimina_producto.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "PRECIO"))
        item = self.tabla_elimina_producto.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "CANTIDAD"))
        self.label_30.setText(_translate("MainWindow", "COD_PRODUCTO"))
        self.label_31.setText(_translate("MainWindow", "TIPO"))
        self.label_32.setText(_translate("MainWindow", "MARCA"))
        self.label_33.setText(_translate("MainWindow", "PRECIO"))
        self.label_34.setText(_translate("MainWindow", "CANTIDAD"))
        self.btn_elimina_producto.setText(_translate("MainWindow", "ELIMINAR"))
        self.label_44.setText(_translate("MainWindow", "ELIMINA PRODUCTO"))
        self.btn_elimina_producto_limpia.setText(_translate("MainWindow", "LIMPIAR"))
        self.label_62.setText(_translate("MainWindow", "BUSCAR"))
        self.label_47.setText(_translate("MainWindow", "VENTA GENERAL"))
        self.btn_agregar_lista_venta.setText(_translate("MainWindow", "AGREGAR A LISTA"))
        self.label.setText(_translate("MainWindow", "ELIJE CLIENTE : "))
        item = self.tabla_lista_venta.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "TIPO PRODUCTO"))
        item = self.tabla_lista_venta.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "COD_PRODUCTO"))
        item = self.tabla_lista_venta.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "COD_CLIENTE"))
        item = self.tabla_lista_venta.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "CANTIDAD"))
        self.label_48.setText(_translate("MainWindow", "ELIJE PRODUCTO : "))
        self.label_49.setText(_translate("MainWindow", "COD_CLIENTE"))
        self.label_98.setText(_translate("MainWindow", "NOMBRE"))
        self.label_99.setText(_translate("MainWindow", "COD_PRODUCTO"))
        self.label_100.setText(_translate("MainWindow", "TIPO"))
        self.label_101.setText(_translate("MainWindow", "CANTIDAD"))
        self.btn_registrar_venta.setText(_translate("MainWindow", "REGISTRAR VENTA"))
        item = self.tabla_cliente_venta.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "COD_CLIENTE"))
        item = self.tabla_cliente_venta.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "NOMBRE"))
        item = self.tabla_cliente_venta.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "DNI"))
        item = self.tabla_cliente_venta.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "TELEFONO"))
        item = self.tabla_cliente_venta.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "SEXO"))
        item = self.tabla_producto_venta.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "COD_PRODUCTO"))
        item = self.tabla_producto_venta.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "TIPO"))
        item = self.tabla_producto_venta.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "MARCA"))
        item = self.tabla_producto_venta.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "PRECIO"))
        item = self.tabla_producto_venta.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "CANTIDAD"))
        self.btn_venta_limpia_tabla.setText(_translate("MainWindow", "LIMPIAR TABLA"))
        self.btn_venta_limpia_datos.setText(_translate("MainWindow", "LIMPIAR DATOS"))
        self.label_55.setText(_translate("MainWindow", "NUM_VENTA"))
        self.label_56.setText(_translate("MainWindow", "FECHA"))
        self.btn_calcula_reporte_mensual.setText(_translate("MainWindow", "CALCULAR REPORTE"))
        self.label_2.setText(_translate("MainWindow", "INGRESA FECHAS PARA EL REPORTE MENSUAL"))
        self.label_3.setText(_translate("MainWindow", "MES"))
        self.cmb_meses_reporte_mensual.setItemText(1, _translate("MainWindow", "ENERO"))
        self.cmb_meses_reporte_mensual.setItemText(2, _translate("MainWindow", "FEBRERO"))
        self.cmb_meses_reporte_mensual.setItemText(3, _translate("MainWindow", "MARZO"))
        self.cmb_meses_reporte_mensual.setItemText(4, _translate("MainWindow", "ABRIL"))
        self.cmb_meses_reporte_mensual.setItemText(5, _translate("MainWindow", "MAYO"))
        self.cmb_meses_reporte_mensual.setItemText(6, _translate("MainWindow", "JUNIO"))
        self.cmb_meses_reporte_mensual.setItemText(7, _translate("MainWindow", "JULIO"))
        self.cmb_meses_reporte_mensual.setItemText(8, _translate("MainWindow", "AGOSTO"))
        self.cmb_meses_reporte_mensual.setItemText(9, _translate("MainWindow", "SEPTIEMBRE"))
        self.cmb_meses_reporte_mensual.setItemText(10, _translate("MainWindow", "OCTUBRE"))
        self.cmb_meses_reporte_mensual.setItemText(11, _translate("MainWindow", "NOVIEMBRE"))
        self.cmb_meses_reporte_mensual.setItemText(12, _translate("MainWindow", "DICIEMBRE"))
        self.cmb_reporte_mensual_anio.setItemText(1, _translate("MainWindow", "2023"))
        self.cmb_reporte_mensual_anio.setItemText(2, _translate("MainWindow", "2022"))
        self.cmb_reporte_mensual_anio.setItemText(3, _translate("MainWindow", "2021"))
        self.label_52.setText(_translate("MainWindow", "AÑO"))
        self.btn_reporte_mensual_limpiar.setText(_translate("MainWindow", "LIMPIAR"))
        self.btn_volver_mensual.setText(_translate("MainWindow", "VOLVER"))
        item = self.tabla_reporte_mensual.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NRO. VENTA"))
        item = self.tabla_reporte_mensual.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FECHA"))
        item = self.tabla_reporte_mensual.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "TIPO PRODUCTO"))
        item = self.tabla_reporte_mensual.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "CLIENTE"))
        self.label_45.setText(_translate("MainWindow", "REPORTE MENSUAL"))
        self.btn_pdf_mensual.setText(_translate("MainWindow", "PDF"))
        self.label_4.setText(_translate("MainWindow", "INGRESA FECHAS PARA EL REPORTE SEMANAL"))
        self.label_35.setText(_translate("MainWindow", "MES"))
        self.btn_calcular_semanal.setText(_translate("MainWindow", "CALCULAR"))
        self.cmb_semanas_reporte_semanal.setItemText(1, _translate("MainWindow", "1"))
        self.cmb_semanas_reporte_semanal.setItemText(2, _translate("MainWindow", "2"))
        self.cmb_semanas_reporte_semanal.setItemText(3, _translate("MainWindow", "3"))
        self.cmb_semanas_reporte_semanal.setItemText(4, _translate("MainWindow", "4"))
        self.cmb_meses_reporte_semanal.setItemText(1, _translate("MainWindow", "ENERO"))
        self.cmb_meses_reporte_semanal.setItemText(2, _translate("MainWindow", "FEBRERO"))
        self.cmb_meses_reporte_semanal.setItemText(3, _translate("MainWindow", "MARZO"))
        self.cmb_meses_reporte_semanal.setItemText(4, _translate("MainWindow", "ABRIL"))
        self.cmb_meses_reporte_semanal.setItemText(5, _translate("MainWindow", "MAYO"))
        self.cmb_meses_reporte_semanal.setItemText(6, _translate("MainWindow", "JUNIO"))
        self.cmb_meses_reporte_semanal.setItemText(7, _translate("MainWindow", "JULIO"))
        self.cmb_meses_reporte_semanal.setItemText(8, _translate("MainWindow", "AGOSTO"))
        self.cmb_meses_reporte_semanal.setItemText(9, _translate("MainWindow", "SEPTIEMBRE"))
        self.cmb_meses_reporte_semanal.setItemText(10, _translate("MainWindow", "OCTUBRE"))
        self.cmb_meses_reporte_semanal.setItemText(11, _translate("MainWindow", "NOVIEMBRE"))
        self.cmb_meses_reporte_semanal.setItemText(12, _translate("MainWindow", "DICIEMBRE"))
        self.label_51.setText(_translate("MainWindow", "SEMANA"))
        self.cmb_reporte_semanal_anio.setItemText(1, _translate("MainWindow", "2023"))
        self.cmb_reporte_semanal_anio.setItemText(2, _translate("MainWindow", "2022"))
        self.cmb_reporte_semanal_anio.setItemText(3, _translate("MainWindow", "2021"))
        self.label_53.setText(_translate("MainWindow", "AÑO"))
        self.btn_reporte_semanal_limpiar.setText(_translate("MainWindow", "LIMPIAR"))
        item = self.tabla_reporte_semanal.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "NRO. VENTA"))
        item = self.tabla_reporte_semanal.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "FECHA"))
        item = self.tabla_reporte_semanal.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "TIPO PRODUCTO"))
        item = self.tabla_reporte_semanal.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "CLIENTE"))
        self.btn_volver_semanal.setText(_translate("MainWindow", "VOLVER"))
        self.label_46.setText(_translate("MainWindow", "REPORTE SEMANAL"))
        self.btn_pdf_semanal.setText(_translate("MainWindow", "PDF"))